name: personaDRIVE
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.10

  # Core Deep Learning
  - pytorch=2.2.0
  - torchvision=0.17.0
  - torchaudio=2.2.0
  - cudatoolkit=11.8  # supprime ou modifie selon GPU

  # Medical Imaging & Radiomics
  - monai=1.3.0
  - pyradiomics=3.0.1
  - simpleitk=2.3.1
  - pydicom=2.4.4
  - nibabel=5.2.0

  # NLP & Clinical Text Processing
  - transformers=4.38.0
  - sentencepiece=0.1.99
  - nltk=3.8.1

  # Data Science Essentials
  - scikit-learn=1.4.0
  - pandas=2.2.0
  - numpy=1.26.0
  - scipy=1.12.0

  # Visualisation
  - matplotlib=3.8.0
  - seaborn=0.13.0
  - plotly=5.19.0

  # Experiment Tracking & Utilities
  - tqdm=4.66.0
  - mlflow=2.11.1
  - wandb=0.16.2
  - pyyaml=6.0.1

  # Jupyter Environment
  - jupyterlab=4.1.5
  - notebook=7.1.2

  # Pip-specific installs (optional)
  - pip
  - pip:
      # Si tu veux des packages non disponibles sur conda-forge
      # Exemple : pour compatibilité spéciale GPU
      # - torch==2.2.0+cu118 --extra-index-url https://download.pytorch.org/whl/cu118
      []
